### ISSUE TITLE
Ubuntu installation error with 1.14 as well

### ISSUE THREAD

**Issue by catch-minie** [hms-dbmi/spp#11]
I am trying to install spp-1.14 on ubuntu , but I am facing following error :

R CMD INSTALL spp-1.14.tar.gz 
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing to library ‘/home/user/R/x86_64-pc-linux-gnu-library/3.3’
* installing *source* package ‘spp’ ...
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for BZ2_bzDecompressInit in -lbz2... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for grep that handles long lines and -e... /bin/grep
checking how to run the C++ preprocessor... g++ -E
checking for a sed that does not truncate output... /bin/sed
configure: Detected BOOST_ROOT; continuing with --with-boost=/var/lib/dpkg/info/libboost1.58-dev
checking for Boost headers version >= 1.41.0... no
configure: error: cannot find Boost headers version >= 1.41.0
ERROR: configuration failed for package ‘spp’
* removing ‘/home/user/R/x86_64-pc-linux-gnu-library/3.3/spp’

**Comment by pkharchenko** [comment]
Seems like you need to install boost libraries:
sudo apt-get install libboost-dev
Best,
-peter.
