### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by daler** [hms-dbmi/spp#15]
@pkharchenko would you mind releasing a new version that has the updates at least in https://github.com/hms-dbmi/spp/commit/b252e090b70e0a2308e6d6829fab6f2f7c041291? The current version 1.14 is still broken for BAM files.

**Comment by pkharchenko** [comment]
Hi Ryan,
 Haven’t had time to look at this, unfortunately. 
 Is there a fix for the bam files that’s been checked in? Actually, I can’t find an issue on the bam parsing. An example would be great to have.
Thanks,
-peter.

**Comment by daler** [comment]
You already have the fix here: https://github.com/hms-dbmi/spp/commit/b252e090b70e0a2308e6d6829fab6f2f7c041291, and there are some other fixes later than that in the master branch. There's just no release yet that includes those changes. All you should need to do is create a new tag (e.g, `1.15`) and push that to github. Github will then build a new tarball automatically and make it available in https://github.com/hms-dbmi/spp/releases.

Then over in https://github.com/bioconda/bioconda-recipes we can build a new package based on that tarball.

Thanks.
