### ISSUE TITLE
spp doesn't see Rsamtools

### ISSUE THREAD

**Issue by ophiothrix** [hms-dbmi/spp#3]
Hello,

I've tried installing spp on the following system:

```
R version 3.2.3 (2015-12-10)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Scientific Linux release 6.5 (Carbon)
```

The library installs and loads fine (I've tried both R CMD INSTALL and GitHub options). But when I try to run read.bam.tags, it fails with the following error:

```
Error in read.bam.tags("batch.download/ENCFF044JXD.bam") : 
  Rsamtools Bioconductor package is now required for BAM file support. Please install
```

But Rsamtools are certainly installed and loaded:

```
other attached packages:
 [1] spp_1.14             caTools_1.17.1       Rsamtools_1.22.0    
 [4] Biostrings_2.38.3    XVector_0.10.0       GenomicRanges_1.22.3
 [7] GenomeInfoDb_1.6.2   IRanges_2.4.6        S4Vectors_0.8.7     
[10] BiocGenerics_0.16.1
```

I wonder if you might have some insight into this issue.

Many thanks!

Aliaksei.

**Comment by ophiothrix** [comment]
Hello again,

I seem to have found the problem and it seems to lie with the code, and (for a change) not the user :) If I look at the read.bam.tags source code, the following block triggers the error:

```
    if (!is.element("fastcluster", installed.packages()[, 1])) {
        stop("Rsamtools Bioconductor package is now required for BAM file support. Please install")
    }
```

But for whatever reason it's checking for presence of fastcluster, and not Rsamtools as suggested by the error message. So I would suggest that either the check or the error message needs to be corrected.

You're welcome.

**Comment by your-highness** [comment]
I second this. In master it is still not fixed.

**Comment by pkharchenko** [comment]
Sorry, somehow I thought the commit was already made. Should be fixed now.
-peter.
