### ISSUE TITLE
Unable to use window.tag.count

### ISSUE THREAD

**Issue by fbrundu** [hms-dbmi/spp#30]
Hi,
I'm trying to call the `window.tag.count` function but I receive the following error:

```R
> library(spp)
> window.tag.count
Error: object 'window.tag.count' not found
```

Is this function available? I see that it is defined [here](https://github.com/hms-dbmi/spp/blob/master/R/zroutines.R).

Thanks,
Francesco

**Comment by fferrari** [comment]
It's not exported due to conflict with R generics.

Call it as spp:::window.tag.count()




Il ven 26 ott 2018, 20:28 Francesco G. Brundu <notifications@github.com> ha
scritto:

**Comment by fbrundu** [comment]
Perfect, thanks!
