### ISSUE TITLE
Was peaks.c function renamed and how to call it?

### ISSUE THREAD

**Issue by fbrundu** [hms-dbmi/spp#31]
Hi,
I'm using a legacy code which contains the call to `peaks.c` in the `spp` package.
I think the code is pointing to the `find_peaks` function exported by [this cpp file](https://github.com/hms-dbmi/spp/blob/692c0b540a0f6257f901259fbb81dd70cfda6a38/src/peaks.cpp). Is it correct?
How to call this function? I tried to list all the methods, exported and non-exported, but I could not find it.

Thanks,
Francesco

**Comment by fferrari** [comment]
You can copy the call to c code function from the R function that calls it
as well.

You can also try the spp version in CRAN repository, it's the same as
GitHub development branch and incorporates a few more minor adjustments to
avoid warnings when compiling C code




Il ven 26 ott 2018, 20:46 Francesco G. Brundu <notifications@github.com> ha
scritto:

**Comment by fbrundu** [comment]
Thanks. I actually didn't find in the github repo where the c code function is called from the R function, sorry.

In the code I'm using, the function `peaks.c` is called right after calling peaks with `spp:::window.tag.count` with the following signature:

    peak.indices <- peaks.c(smoothed.density[[chr]]$y, thr = thr, max.span = span)

used to calculate index positions of all local maxima on the density vector. I didn't understand if a new function is used instead in the new spp version. I also installed it from CRAN but I'm unable to find the function in the package, probably it is obsolete?

**Comment by fferrari** [comment]
Can you paste the code of your peak.c function?




Il ven 26 ott 2018, 21:28 Francesco G. Brundu <notifications@github.com> ha
scritto:

**Comment by fbrundu** [comment]
The `peaks.c` function is defined at [this github repo](https://github.com/JEFworks/Supplementary-Code/blob/ab5b300c5ebb5dbd460adf585116941d184edb48/snDropSeq_scTHSseq/spp_comb.R#L179). It was provided as supplementary code.

**Comment by fferrari** [comment]
This is where you call the C code.

results <- .Call("find_peaks",x,thr,max.span,"spp");

It looks correct.

Not sure what is not working in your case.





Il ven 26 ott 2018, 21:45 Francesco G. Brundu <notifications@github.com> ha
scritto:

**Comment by pkharchenko** [comment]
Hmm .. the definition of the function looks correct, though it was never an official part of the spp …
I would try adding it to the package R code, as an exported function … though on my machine it works fine as an outside code calling find_peaks in spp:

> # find positions of all local maxima above some threshold
> peaks.c <- function(x,thr=min(x),max.span=1) {
>   storage.mode(x) <- storage.mode(thr) <- "double";
>   storage.mode(max.span) <- "integer";
>   results <- .Call("find_peaks",x,thr,max.span,”spp");
>   return(results);
> }


Best,
-peter.

**Comment by fbrundu** [comment]
Thanks Dr. Kharchenko. Was the comment about adding it to the package R code directed to me or to the package maintainers? I tested it on a linux virtual machine with this setup (versions and packages):

```R
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] BSgenome.Hsapiens.UCSC.hg38.masked_1.3.99
 [2] BSgenome.Hsapiens.UCSC.hg38_1.4.1
 [3] BSgenome_1.44.2
 [4] rtracklayer_1.36.6
 [5] Biostrings_2.44.2
 [6] XVector_0.16.0
 [7] GenomicRanges_1.28.6
 [8] GenomeInfoDb_1.12.3
 [9] IRanges_2.10.5
[10] S4Vectors_0.14.7
[11] BiocGenerics_0.22.1
[12] spp_1.15.5
[13] Rcpp_0.12.19

loaded via a namespace (and not attached):
 [1] zlibbioc_1.22.0            GenomicAlignments_1.12.2
 [3] BiocParallel_1.10.1        lattice_0.20-35
 [5] caTools_1.17.1.1           tools_3.4.0
 [7] SummarizedExperiment_1.6.5 grid_3.4.0
 [9] Biobase_2.36.2             matrixStats_0.54.0
[11] Matrix_1.2-14              GenomeInfoDbData_0.99.0
[13] bitops_1.0-6               RCurl_1.95-4.11
[15] DelayedArray_0.2.7         compiler_3.4.0
[17] Rsamtools_1.28.0           XML_3.98-1.16
```

but still I get:

```R
Error in .Call("find_peaks", x, thr, max.span, "spp") :
  C symbol name "find_peaks" not in load table
```

The only library installed is `/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.4/spp/libs/spp.so`. I also tried:

```R
> dyn.load("/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.4/spp/libs/spp.so")
> peak.indices <- peaks.c(smoothed.density[[chr]]$y, thr = thr, max.span = span)
Error in .Call("find_peaks", x, thr, max.span, "spp") :
  C symbol name "find_peaks" not in load table
```

I can help adding to the package R code, if it's something that can be done by adding it to [the zroutines R source](https://github.com/hms-dbmi/spp/blob/master/R/zroutines.R).

Thanks,
Best,
Francesco

**Comment by fbrundu** [comment]
Fixed in https://github.com/hms-dbmi/spp/pull/32
Feel free to reject if not necessary for this library.

Thanks
