### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by chelauk** [hms-dbmi/spp#35]
I am attempting to install spp on Red Hat Enterprise Linux Server release 7.4 (Maipo)
R version 3.6.0 (2019-04-26) -- "Planting of a Tree"

using install.packages

compilation goes fine until:

** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘spp’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/lustre/home/user/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-spp/00new/spp/libs/spp.so':
  /shared/ucl/apps/gcc/4.9.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /lustre/home/user/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-spp/00new/spp/libs/spp.so)
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/lustre/home/user/R/x86_64-pc-linux-gnu-library/3.6/spp’

I do not have root privileges on this system,

any advice?

Many thanks

**Comment by carmencita** [comment]
Hi Chelauk,
sorry for the late reply.
The problem is not caused by spp but by a missing library  (libstdc++.so). You can install the library system-wide (ask your system administrator) or locally.
Kind regards
