### ISSUE TITLE
have some problem with runmean

### ISSUE THREAD

**Issue by fengchuiguo1994** [hms-dbmi/spp#36]
like this

Loading required package: Rcpp
Error in runmean(cc$y, sbw, alg = "fast") : 
  could not find function "runmean"
Execution halted

i don't know how to solve it

**Comment by carmencita** [comment]
Hi,
runmean() is a function of the caTools package.
Is caTools installed?

**Comment by fengchuiguo1994** [comment]
thank you , i add the command "library(caTools)"  into run_spp.R
